# サイト設定
title: ノマドマジック株式会社
email: info@nomadmagic.co.jp
description: >-
  仮想化されたワークプレイス（働く環境）のクラウドサービスでの提供を行う
  ノマドマジック株式会社の公式ウェブサイトです。
baseurl: ""
url: "https://nomadmagic.github.io"

# 会社情報
company:
  name: ノマドマジック株式会社
  established: 2019年10月1日
  address: 〒100-0004東京都千代田区大手町1-5-1大手町ファーストスクエア イーストタワー4階
  business: 仮想化されたワークプレイス（働く環境）のクラウドサービスでの提供
  capital: 9,000,000円
  president: 代表取締役 丸山 良弘

# ビルド設定
markdown: kramdown
highlighter: rouge
permalink: pretty

# プラグイン
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# 除外ファイル
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# デフォルト設定
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "ノマドマジック株式会社"
  - scope:
      path: ""
    values:
      layout: "default"

# ページネーション
paginate: 5
paginate_path: "/news/page:num/"

# SEO設定
lang: ja
timezone: Asia/Tokyo

# ソーシャルメディア
social:
  name: ノマドマジック株式会社
  links: []

# Google Analytics (必要に応じて設定)
# google_analytics: UA-XXXXXXXXX-X 